# =====================================================
# =====================================================
# =====================================================

server:
  port: 8083

spring:
  application:
    name: backend-log4shell

# 顯示 banner
  main:
    banner-mode: console

logging:
  level:
    root: INFO
    com.owasp.log4shell: DEBUG
